apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
          name: http
          protocol: TCP
        env:
        - name: VITE_API_URL
          value: "https://server.pern-stack.local.getwebstack.dev/api"
      restartPolicy: Always
